version: '2'
services:
    app:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on: 
            - db
        links:
            - db
    db:
        image: postgres:16.1-alpine3.19
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
            - POSTGRES_DB=dev
volumes:
    postgres-data:
