version: '2'
services:
    app:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/app
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
        depends_on: 
            - db
        links:
            - db
    db:
        image: postgres:10.4-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
