from .base import *

DEBUG = False

ALLOWED_HOSTS = []

SECRET_KEY = os.getenv('SECRET_KEY')

SECURE_HSTS_SECONDS = 30
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
